theme: jekyll-theme-minimal
title: J. Yim Tutors
description: <i>In-person and virtual private tutoring for Mathematics and English.</i><br><br> Please use the <b><a href='https://forms.gle/o6eoyh9jLhDVupT49'>Inquiry Form</a></b> if you have any clarification questions or would like to schedule a call to answer questions and the <b><a href='https://forms.gle/B7nPjUd3jYMAcdGz9'>Tutoring Request Form</a></b> if you would like to engage services.
