theme: jekyll-theme-minimal
title: J. Yim Tutors
description: In-person and virtual private tutoring for Mathematics and English. Please use the <a href='https://forms.gle/o6eoyh9jLhDVupT49'>Inquiry Form</a> if you have any clarification questions or would like to schedule a call to answer questions and the <a href='https://forms.gle/B7nPjUd3jYMAcdGz9'>Tutoring Request Form</a> if you would like to engage services. 
